apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: health-exporter
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/ElsaDevOps/Observability-EKS
    targetRevision: main
    path: k8s/overlays/dev
  destination:
    server: https://kubernetes.default.svc
    namespace: health-exporter
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
