resources:
- ../../base
namePrefix: dev-
namespace: health-exporter
patches:
- path: deployment-patch.yaml
- path: configmap-patch.yaml
images:
- name: 313196411727.dkr.ecr.eu-west-2.amazonaws.com/my-exporter
  newName: 313196411727.dkr.ecr.eu-west-2.amazonaws.com/my-exporter
  newTag: 7a26a802295513e5e4284c02635d4eb22176999e
- name: 313196411727.dkr.ecr.eu-west-2.amazonaws.com/my-exporter:latest
  newTag: initial
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
