resources:
- ../../base
namePrefix: dev-
namespace: health-exporter
patches:
  - path: deployment-patch.yaml
  - path: configmap-patch.yaml
images:
- name: 313196411727.dkr.ecr.eu-west-2.amazonaws.com/my-exporter:latest
  newTag: initial
